name: photo-booth
base: core24
version: '0.1.0'
summary: A full-screen, touch-friendly photobooth application for Linux.
description: |
  A full-screen, touch-friendly photobooth application created for Linux. This app displays a live view from a selected camera, allows you to take photos, and includes several customization options.

grade: stable
confinement: strict

apps:
  photo-booth:
    command: bin/launcher
    extensions: [gnome]
    environment:
      PYTHONPATH: $SNAP/lib/python3.12/site-packages:$PYTHONPATH
    plugs:
      - home
      - camera
      - network
      - audio-record
      - audio-playback

parts:
  photobooth:
    plugin: python
    source: .
    override-build: |
      python3 -m venv venv_photobooth
      source venv_photobooth/bin/activate
      pip3 install -r requirements.txt
      cp -a venv_photobooth/* $CRAFT_PART_INSTALL/
      cp *.py $CRAFT_PART_INSTALL/
      cp -rp assets $CRAFT_PART_INSTALL/

  deps:
    plugin: nil
    stage-packages:
      - v4l-utils
      - libportaudio2

    prime:
      - usr/bin/v4l2*
      - usr/lib/*/libasound*.so.*
      - usr/lib/*/libjack*.so.*
      - usr/lib/*/libportaudio.so.*
      - usr/lib/*/libv4l2rds.so*

  launcher:
    plugin: dump
    source: files/
    organize:
      launcher.sh: bin/launcher
