name: photo-booth
base: core24
version: '0.1.0'
summary: A full-screen, touch-friendly photobooth application for Linux.
description: |
  A full-screen, touch-friendly photobooth application created for Linux. This app displays a live view from a selected camera, allows you to take photos, and includes several customization options.

grade: stable
confinement: strict

apps:
  photo-booth:
    command: bin/launcher
    extensions: [gnome]
    plugs:
      - camera
      - network

parts:
  photobooth:
    plugin: python
    source: .
    override-build: |
      snapcraftctl build
      python3 create_assets.py
    build-packages:
      - libv4l-dev
    stage-packages:
      - v4l-utils
      - libgl1
      - libgl1-mesa-glx
    python-packages:
      - -r requirements.txt

  launcher:
    plugin: dump
    source: files/
    organize:
      launcher.sh: bin/launcher
